apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: gpu-cluster-queue
spec:
  namespaceSelector: {}   # allow all namespaces (or restrict via a selector)
  resourceGroups:
    - coveredResources: ["nvidia.com/gpu"]
      flavors:
        - name: gpu-node-a
          resources:
            - name: "nvidia.com/gpu"
              nominalQuota: 1
        - name: gpu-node-b
          resources:
            - name: "nvidia.com/gpu"
              nominalQuota: 1

