apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cq-team-a
spec:
  cohort: cpu-shared
  namespaceSelector: {}                  # allow any namespace (we'll restrict via LQ)
  resourceGroups:
    - coveredResources: ["cpu","memory"]
      flavors:
        - name: default-flavor
          resources:
            - name: "cpu"
              nominalQuota: 2
              borrowingLimit: 2
            - name: "memory"
              nominalQuota: 4Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cq-team-b
spec:
  cohort: cpu-shared
  namespaceSelector: {}
  resourceGroups:
    - coveredResources: ["cpu","memory"]
      flavors:
        - name: default-flavor
          resources:
            - name: "cpu"
              nominalQuota: 2
              borrowingLimit: 2
            - name: "memory"
              nominalQuota: 4Gi
