apiVersion: batch/v1
kind: Job
metadata:
  name: team-a-borrow-demo
  namespace: team-a
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  parallelism: 3
  completions: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: busybox
          command: ["sh","-c","echo Team A running; sleep 120; echo done"]
          resources:
            requests:
              cpu: "1"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "256Mi"
