apiVersion: batch/v1
kind: Job
metadata:
  name: kueue-demo-job
  namespace: kueue-demo
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: busybox
          command: ["sh", "-c", "echo 'Job admitted!'; sleep 15; echo 'Done.'"]
          resources:
            requests:
              cpu: "1"
              memory: "256Mi"
