apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-job-
  namespace: kueue-demo
  annotations:
    kueue.x-k8s.io/queue-name: cluster-queue
spec:
  parallelism: 3
  completions: 3
  template:
    spec:
      containers:
      - name: example
        image: registry.example/batch/calc:latest
        args: ["30s"]
        resources:
          requests:
            cpu: 1
      restartPolicy: Never
