apiVersion: batch/v1
kind: Job
metadata:
  name: demo-gpu-2pods
  namespace: kueue-demo
  labels:
    kueue.x-k8s.io/queue-name: gpu-queue
spec:
  parallelism: 2
  completions: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: nvidia/cuda:12.3.1-base-ubuntu22.04
          command: ["bash", "-lc", "nvidia-smi || echo 'no nvidia-smi'; sleep 20"]
          resources:
            limits:
              nvidia.com/gpu: 1
